"""Champion strategy: live screen + backtest with the TimesFM P20 volume veto.

This is the FINAL autoresearch champion (iter83, max_holdings=2): the top-500
S&P 500 (SPY) momentum-rotation strategy tuned to maximize worst_year_sharpe
(the minimum annual Sharpe across full years 2015-2025).

Usage:
  python run_champion.py backtest                    # Reproduce the iter83 champion result
  python run_champion.py live                        # Screen the current session
  python run_champion.py live --as-of 2026-06-01     # Screen a specific date
  python run_champion.py live --current-positions positions.csv
  python run_champion.py live --refresh-data         # Force refresh cached data

The champion config is config/research.json (SPY universe, limit 500) and the
tuned parameters are research_params.json (applied via overfit_harness.apply_params_to_config):
  max_holdings=2, ts_mom=10/0, sma=3/50/210, P20 quantile veto (threshold 0.35,
  ctx=256, horizon=21), vol_scaled_weights (lookback 21), conviction tilt
  (weight_tilt=0.17, conf_tilt, conf_tilt_pow=50, vol-adjusted, vol_pow=4),
  fund_weight=0.02, macro=-0.5/-1.0, min_volume=11M, cost=3bps.

backtest mode delegates to overfit_harness.run_benchmark (perturbation off) so
the result is byte-for-byte identical to the autoresearch champion.
live mode reuses the harness veto/sizing helpers (build_veto_mask, _size_weights)
so the live screen uses the exact same P20 veto + conviction-tilt sizing.

S&P 500 holdings auto-update: load_market_context fetches the current constituents
from Wikipedia (cache/sp500_holdings.csv, fresh within 7 days) when etf_ticker==SPY,
so each run sees the latest S&P 500 as it rebalances. TimesFM forecasts for any
NEW symbols must be generated by re-running `python generate_spy_forecasts.py
--quantiles` (it only forecasts missing (symbol, date) pairs; idempotent).
"""
from __future__ import annotations

import json
import sys
import time
import warnings
import os
from pathlib import Path
from types import SimpleNamespace

warnings.filterwarnings("ignore")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")

import numpy as np
import pandas as pd

sys.path.insert(0, "src")
sys.path.insert(0, "experiments")

from algo_trading.timesfm_experiments import (
    load_context, build_factor_state, set_config,
    benchmark_close, score_composite, eligible_symbols,
    load_forecast_panel,
)
from algo_trading.config import AppConfig
from algo_trading.calendar_utils import is_rebalance_session, next_rebalance_session

import overfit_harness
from overfit_harness import apply_params_to_config, build_veto_mask, _size_weights

CONFIG_PATH = "config/research.json"
PARAMS_PATH = "research_params.json"
CTX, HOR = 256, 21


def _load_params() -> dict:
    with open(PARAMS_PATH) as f:
        return json.load(f)


def run_backtest() -> int:
    """Reproduce the iter83 champion backtest (delegates to the overfit harness).

    perturb_runs=0 skips the perturbation loop and emits the single deterministic
    champion run, byte-for-bit identical to the autoresearch result.
    """
    print(f"Reproducing iter83 champion: {CONFIG_PATH} + {PARAMS_PATH}", flush=True)
    print(f"Strategy: SPY top-500, max_holdings=2, P20 quantile veto, conviction tilt, vol-adjusted (vol_pow=4)", flush=True)
    print(f"Primary metric: worst_year_sharpe (target = 0.596, all 11 years 2015-2025 positive)", flush=True)
    print("-" * 80, flush=True)
    args = SimpleNamespace(
        config=CONFIG_PATH,
        params=PARAMS_PATH,
        perturb_runs=0,
        perturb_sigma=0.03,
        seed=42,
    )
    return overfit_harness.run_benchmark(args)


def _champion_live_setup(state, ctx, params, bench, sessions, dates_limit=None):
    """Build the champion veto mask + sizing inputs (PIT-safe).

    Reuses overfit_harness.build_veto_mask (which builds base_scores for all
    rebalance dates) and replicates the harness's vol_prior_frame, vol_factor_map,
    and median_gap computation so the live single-date sizing matches the
    backtest exactly. dates_limit optionally restricts to dates <= a live session.
    """
    N = int(params["max_holdings"])
    veto_threshold = float(params.get("veto_threshold", 0.35))
    trailing_window = int(params.get("trailing_vol_window", 21))
    veto_horizon = int(params.get("veto_horizon", 21))
    use_quantile_veto = bool(params.get("use_quantile_veto", True))
    quantile_col = int(params.get("quantile_col", 1))

    if use_quantile_veto:
        qpanel = load_forecast_panel(CTX, HOR, kind="volume", quantiles=True)
        if qpanel is None:
            raise RuntimeError("No quantile volume forecast cache (run: python generate_spy_forecasts.py --quantiles)")
        qcols = [f"q{quantile_col}_h{h}" for h in range(veto_horizon)]
        pred_vol = qpanel[qcols].sum(axis=1) / veto_horizon
        pred_vol = pred_vol.unstack(level="symbol")
    else:
        from algo_trading.timesfm_engine import mean_forecast_sum
        panel = load_forecast_panel(CTX, HOR, kind="volume", quantiles=False)
        if panel is None:
            raise RuntimeError("No volume forecast cache")
        pred_vol = mean_forecast_sum(panel, veto_horizon) / veto_horizon
        pred_vol = pred_vol.unstack(level="symbol")

    veto_mask, base_scores, prior_ends, dates = build_veto_mask(
        state, ctx, pred_vol, veto_threshold, trailing_window)

    vol_scaled = bool(params.get("vol_scaled_weights", False))
    vol_lookback = int(params.get("vol_lookback", 21))
    vol_prior_frame = None
    if vol_scaled:
        ret_std = ctx.prices.close.pct_change().rolling(vol_lookback, min_periods=10).std()
        vol_prior_frame = ret_std.reindex(prior_ends)
        vol_prior_frame.index = pd.DatetimeIndex(dates)

    # Conviction-tilt inputs (replicates overfit_harness.run_benchmark).
    weight_tilt = float(params.get("weight_tilt", 0.0))
    conf_tilt = bool(params.get("conf_tilt", False))
    conf_tilt_pow = float(params.get("conf_tilt_pow", 1.0))
    conf_tilt_vol = bool(params.get("conf_tilt_vol", False))
    median_gap = None
    vol_factor_map = None
    if conf_tilt:
        _gaps = []
        for _d, _sc in base_scores.items():
            _s = _sc.replace([np.inf, -np.inf], np.nan).dropna()
            if len(_s) >= 2:
                _t = _s.sort_values(ascending=False).head(2)
                _gaps.append(abs(float(_t.iloc[0]) - float(_t.iloc[1])))
        median_gap = float(np.median(_gaps)) if _gaps else None
        if conf_tilt_vol:
            _vw = int(params.get("conf_tilt_vol_window", 21))
            _vcap = float(params.get("conf_tilt_vol_cap", 2.0))
            _vpow = float(params.get("conf_tilt_vol_pow", 1.0))
            _bv = bench.pct_change().rolling(_vw, min_periods=5).std()
            _pem = dict(zip(dates, prior_ends))
            _vols = [float(_bv.loc[pe]) for pe in [_pem.get(d) for d in dates]
                     if pe is not None and pe in _bv.index and np.isfinite(_bv.loc[pe]) and _bv.loc[pe] > 0]
            _mv = float(np.median(_vols)) if _vols else 1.0
            vol_factor_map = {}
            for d in dates:
                pe = _pem.get(d)
                vf = 1.0
                if pe is not None and pe in _bv.index and _mv > 0:
                    v = float(_bv.loc[pe])
                    if np.isfinite(v) and v > 0:
                        vf = min(_vcap, (v / _mv) ** _vpow) if _vpow != 1.0 else min(_vcap, v / _mv)
                vol_factor_map[d] = vf

    return {
        "N": N, "veto_mask": veto_mask, "base_scores": base_scores,
        "vol_prior_frame": vol_prior_frame, "vol_scaled": vol_scaled,
        "weight_tilt": weight_tilt, "conf_tilt": conf_tilt,
        "conf_tilt_pow": conf_tilt_pow, "conf_tilt_vol": conf_tilt_vol,
        "median_gap": median_gap, "vol_factor_map": vol_factor_map,
        "dates": dates, "pred_vol": pred_vol, "veto_horizon": veto_horizon,
    }


def run_live(as_of: str | None = None, current_positions_path: str | None = None, refresh: bool = False) -> int:
    """Screen the current session with the iter83 champion (P20 veto + sizing)."""
    t0 = time.time()
    params = _load_params()
    cfg, ctx = load_context(CONFIG_PATH, refresh=refresh)
    cfg = apply_params_to_config(cfg, params)
    set_config(cfg)

    state = build_factor_state(ctx, cfg)
    sessions = ctx.prices.sessions
    bench = benchmark_close(ctx, "SPY")

    # Determine the session to screen
    target = pd.Timestamp(as_of).normalize() if as_of else pd.Timestamp.today().normalize()
    loaded = sessions[sessions <= target]
    if loaded.empty:
        print(f"ERROR: no session at or before {target.date()}", file=sys.stderr)
        return 1
    session = loaded[-1]

    # Freshness guard: if the loaded session lags the target by more than a few
    # calendar days, price data is likely stale (yfinance outage / missed
    # refresh) and the rebalance decision would silently flip. Surface it loudly
    # so the operator does not act on a stale session.
    session_lag_days = int((target - session).days)
    stale_price = session_lag_days > 4
    if stale_price:
        print(f"WARNING: latest loaded price session is {session.date()} ({session_lag_days}d behind target "
              f"{target.date()}) -- price data may be stale. Re-run with --refresh-data.", file=sys.stderr)

    rebalance_due = is_rebalance_session(session, sessions, cfg.strategy.rebalance_frequency)
    try:
        next_rebal = next_rebalance_session(session, sessions, cfg.strategy.rebalance_frequency)
    except ValueError:
        next_rebal = pd.NaT

    N = int(params["max_holdings"])

    # Build the champion setup over all history (PIT-safe) for median_gap/vol_factor.
    setup = _champion_live_setup(state, ctx, params, bench, sessions)
    base_scores = setup["base_scores"]
    veto_mask = setup["veto_mask"]
    pred_vol = setup["pred_vol"]

    # Forecast coverage check for the live session (forward-fill from the most
    # recent forecast date <= session; PIT-safe). Warn if no coverage -> veto off.
    live_veto_on = False
    forecast_date_used = None
    if session in pred_vol.index:
        live_veto_on = True
        forecast_date_used = session
    else:
        prior_fc = pred_vol.index[pred_vol.index <= session]
        if len(prior_fc) > 0:
            live_veto_on = True  # build_veto_mask ffills to the session
            forecast_date_used = prior_fc[-1]
    # Surface forecast staleness: build_veto_mask ffills predicted volume from
    # the most recent cached forecast date, so a frozen cache silently vetoes on
    # months-old predictions while still reporting "coverage ON". Track the actual
    # date so the operator can see the veto is stale.
    forecast_age_days = int((session - forecast_date_used).days) if forecast_date_used is not None else None
    stale_forecast = forecast_age_days is not None and forecast_age_days > 35

    if not live_veto_on:
        veto_cov = "off"
        veto_cov_label = "OFF — run generate_spy_forecasts.py --quantiles"
    elif stale_forecast:
        veto_cov = "stale"
        veto_cov_label = f"STALE (ffilled from {forecast_date_used.date()}, {forecast_age_days}d old)"
    else:
        veto_cov = "on"
        veto_cov_label = "ON (P20 quantile)"

    if session not in base_scores:
        print(f"Champion Screen — {session.date()}")
        print(f"Rebalance due: {'yes' if rebalance_due else 'no'}")
        print(f"Next rebalance: {next_rebal.date() if pd.notna(next_rebal) else 'N/A'}")
        print("No eligible stocks found (macro risk-off or no candidates).")
        print(f"RESULT session={session.date()} rebalance={'yes' if rebalance_due else 'no'} action=NONE symbol=NA "
              f"vetoed=0 veto_cov={veto_cov} session_lag={session_lag_days} runtime={time.time()-t0:.1f}s")
        return 0

    sc = base_scores[session]
    # Apply the P20 veto for this session
    vetoed = []
    if session in veto_mask.index and live_veto_on:
        vet = veto_mask.loc[session]
        vetoed = sorted(set(vet[vet].index) & set(sc.index))
        sc = sc.drop(index=[s for s in vetoed if s in sc.index])
    elif not live_veto_on:
        print(f"WARNING: no TimesFM forecast coverage for {session.date()} (cache ends before this session).",
              file=sys.stderr)
        print(f"WARNING: veto is OFF for this session. Run `python generate_spy_forecasts.py --quantiles` to "
              f"forecast new (symbol, date) pairs, then re-screen.", file=sys.stderr)
    if live_veto_on and stale_forecast:
        print(f"WARNING: TimesFM forecast for {session.date()} is ffilled from {forecast_date_used.date()} "
              f"({forecast_age_days}d old). Veto may be stale. Run `python generate_spy_forecasts.py --quantiles`.",
              file=sys.stderr)

    # Champion sizing (conviction tilt + vol-adjusted, reusing the harness helper)
    weights = _size_weights(
        sc, N, session, setup["vol_prior_frame"], setup["vol_scaled"],
        weight_tilt=setup["weight_tilt"], conf_tilt=setup["conf_tilt"],
        median_gap=setup["median_gap"], conf_tilt_pow=setup["conf_tilt_pow"],
        conf_tilt_vol=setup["conf_tilt_vol"], vol_factor_map=setup["vol_factor_map"],
    )

    # Load current positions
    current_holdings = set()
    if current_positions_path and Path(current_positions_path).exists():
        pos_df = pd.read_csv(current_positions_path)
        pos_df.columns = [c.strip().lower() for c in pos_df.columns]
        if "symbol" in pos_df.columns:
            current_holdings = set(pos_df["symbol"].astype(str).str.upper().str.strip())

    holdings_meta = ctx.holdings.set_index("ticker") if hasattr(ctx, "holdings") else pd.DataFrame()

    output_rows = []
    ranked = sorted(weights.items(), key=lambda kv: kv[1], reverse=True)
    for rank, (sym, w) in enumerate(ranked, 1):
        name = holdings_meta.loc[sym, "name"] if sym in holdings_meta.index else ""
        sector = holdings_meta.loc[sym, "sector"] if sym in holdings_meta.index else ""
        action = "HOLD" if sym in current_holdings else "BUY"
        output_rows.append({
            "rank": rank, "symbol": sym, "name": name, "sector": sector,
            "weight": f"{w:.4f}", "composite_score": f"{sc.get(sym, float('nan')):.6f}",
            "action": action,
            "vetoed_symbols": ",".join(vetoed) if vetoed else "",
        })
    # SELL rows: any currently-held symbol that dropped out of the target list
    # so the operator sees explicit exit instructions (not a silent disappearance).
    target_symbols = {sym for sym, _ in ranked}
    for sym in sorted(current_holdings - target_symbols):
        name = holdings_meta.loc[sym, "name"] if sym in holdings_meta.index else ""
        sector = holdings_meta.loc[sym, "sector"] if sym in holdings_meta.index else ""
        output_rows.append({
            "rank": "", "symbol": sym, "name": name, "sector": sector,
            "weight": "0.0000", "composite_score": "", "action": "SELL",
            "vetoed_symbols": "",
        })
    output_df = pd.DataFrame(output_rows)

    output_dir = Path("artifacts/live")
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = session.strftime("%Y%m%d")
    screen_path = output_dir / f"champion_screen_{stamp}.csv"
    output_df.to_csv(screen_path, index=False)

    print(f"Champion Screen (iter83, max_holdings={N}) — {session.date()}")
    print(f"Rebalance due: {'yes' if rebalance_due else 'no'}")
    print(f"Next rebalance: {next_rebal.date() if pd.notna(next_rebal) else 'N/A'}")
    print(f"Veto coverage: {veto_cov_label}")
    print(f"Vetoed stocks: {len(vetoed)} ({', '.join(vetoed) if vetoed else 'none'})")
    print()
    if not output_df.empty:
        print(output_df.to_string(index=False))
    else:
        print("No stocks passed all filters.")
    print()
    print(f"Saved screen to {screen_path}")
    print(f"Runtime: {time.time()-t0:.1f}s")

    rebal_flag = "yes" if rebalance_due else "no"
    top_action = output_rows[0]["action"] if output_rows else "NONE"
    top_symbol = output_rows[0]["symbol"] if output_rows else "NA"
    print(f"RESULT session={session.date()} rebalance={rebal_flag} action={top_action} symbol={top_symbol} "
          f"vetoed={len(vetoed)} veto_cov={veto_cov} session_lag={session_lag_days} runtime={time.time()-t0:.1f}s")
    return 0


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python run_champion.py [backtest|live] [--as-of DATE] [--current-positions FILE] [--refresh-data]")
        return 1

    command = sys.argv[1]
    as_of = None
    current_positions = None
    refresh = False
    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == "--as-of" and i + 1 < len(sys.argv):
            as_of = sys.argv[i + 1]; i += 2
        elif sys.argv[i] == "--current-positions" and i + 1 < len(sys.argv):
            current_positions = sys.argv[i + 1]; i += 2
        elif sys.argv[i] == "--refresh-data":
            refresh = True; i += 1
        else:
            i += 1

    if command == "backtest":
        return run_backtest()
    elif command == "live":
        return run_live(as_of=as_of, current_positions_path=current_positions, refresh=refresh)
    else:
        print(f"Unknown command: {command}")
        print("Usage: python run_champion.py [backtest|live]")
        return 1


if __name__ == "__main__":
    sys.exit(main())
